### ISSUE TITLE
torch err

### ISSUE THREAD

**Issue by AnjanaSivaprasad** [AIStream-Peelout/flow-forecast#113]
Hi,,

I am getting below error while running trainer.py

runfile('C:/Users/nanma/Anjana/Research/GithubRepo/ResearchRepo/7_Transformer/flow-forecast/flood_forecast/trainer.py', wdir='C:/Users/nanma/Anjana/Research/GithubRepo/ResearchRepo/7_Transformer/flow-forecast/flood_forecast')
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Traceback (most recent call last):

  File "C:\Users\nanma\Anjana\Research\GithubRepo\ResearchRepo\7_Transformer\flow-forecast\flood_forecast\trainer.py", line 7, in <module>
    from flood_forecast.pytorch_training import train_transformer_style

  File "C:\Users\nanma\AppData\Local\Continuum\anaconda3\envs\flowforecast\lib\site-packages\flood_forecast-0.4.dev0-py3.7.egg\flood_forecast\pytorch_training.py", line 1, in <module>
    import torch

  File "C:\Users\nanma\AppData\Local\Continuum\anaconda3\envs\flowforecast\lib\site-packages\torch\__init__.py", line 127, in <module>
    raise err

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\nanma\AppData\Local\Continuum\anaconda3\envs\flowforecast\lib\site-packages\torch\lib\asmjit.dll" or one of its dependencies.

Is this related to torch installation?

![image](https://user-images.githubusercontent.com/35728425/90318871-17a11880-df51-11ea-810e-c529f1e4dd2f.png)

**Comment by isaacmg** [comment]
Let me look into it. It is probably related to Windows in some way.

**Comment by AnjanaSivaprasad** [comment]
Problem solved by downgrade PyTorch version to 1.5.1

https://stackoverflow.com/questions/63187161/error-while-import-pytorch-module-the-specified-module-could-not-be-found
