### ISSUE TITLE
Informer compatibility with interpretability methods

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#319]
Currently Informer does not work with the shap interpretability methods.  Refactoring SHAP to work with these methods will likely require so significant refactoring. As with Informer we have the target being passed. We should also likely design a helper function to better help with this. 
`
 history, _, forecast_start_idx = csv_test_loader.get_from_start_date(datetime_start)
  background_tensor = _prepare_background_tensor(csv_test_loader)
`

**Comment by isaacmg** [comment]
This still hasn't been fixed. The PR was rushed through to solve some other issues. We will continue to work on the SHAP compatibility in the next....

**Comment by isaacmg** [comment]
ERROR Run icyz07bb errored: ValueError('too many values to unpack (expected 3)')

**Comment by isaacmg** [comment]
(src_data, temporal_feat), (tar_temp, trg_data), all_rows_orig, target_idx_start

**Comment by isaacmg** [comment]
To sum this up this is essentially occuring because the TemporalTestLoader returns four values instead of three. Since we will have other data loaders that may return other values in the future I'd suggest we design a separate function called handle `def handle_dl_output(dl_type,` .  We will then need to modify the following functions:
`def _prepare_background_tensor`
`def deep_explain_model_summary_plot`
`shap.DeepExplainer`?

**Comment by isaacmg** [comment]
https://github.com/slundberg/shap/blob/9411b68e8057a6c6f3621765b89b24d82bee13d4/shap/explainers/_deep/deep_pytorch.py#L137 So SHAP does have multi input support provided elements are in a list. Helper function will need to incorporate this.

**Comment by isaacmg** [comment]
Okay I'll create a PR to address this now. It is kind of pain but we need support for SHAP type models.

**Comment by isaacmg** [comment]
Still running into issues 
```
Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
Traceback (most recent call last):
  File "flood_forecast/trainer.py", line 144, in <module>
    main()
  File "flood_forecast/trainer.py", line 139, in main
    train_function(training_config["model_type"], training_config)
  File "flood_forecast/trainer.py", line 78, in train_function
    {})
  File "/home/circleci/repo/flood_forecast/evaluator.py", line 186, in evaluate_model
    model, test_data, inference_params["datetime_start"]
  File "/home/circleci/repo/flood_forecast/explain_model_output.py", line 93, in deep_explain_model_summary_plot
    shap_values = np.stack(shap_values)
  File "<__array_function__ internals>", line 6, in stack
  File "/usr/local/lib/python3.7/site-packages/numpy/core/shape_base.py", line 421, in stack
    arrays = [asanyarray(arr) for arr in arrays]
  File "/usr/local/lib/python3.7/site-packages/numpy/core/shape_base.py", line 421, in <listcomp>
    arrays = [asanyarray(arr) for arr in arrays]
  File "/usr/local/lib/python3.7/site-packages/numpy/core/_asarray.py", line 171, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not broadcast input array from shape (10,3) into shape (1,)
```
