### ISSUE TITLE
Error when running on flow data

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#61]
```
[356 rows x 22 columns]
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/wandb_agent.py", line 64, in _start
    function()
  File "<ipython-input-5-7aaaa3e75a9d>", line 38, in <lambda>
    wandb.agent(sweep_full, lambda:train_function("PyTorch", make_config_file(file_path_name, gage_id, station_id, correct_file, prev_config["pretrained_rivers"])))
  File "/content/github_aistream-peelout_flow-forecast/flood_forecast/trainer.py", line 58, in train_function
    alpha=0.25)
  File "/content/github_aistream-peelout_flow-forecast/flood_forecast/plot_functions.py", line 33, in plot_df_test_with_confidence_interval
    ci_upper)
  File "/content/github_aistream-peelout_flow-forecast/flood_forecast/plot_functions.py", line 11, in calculate_confidence_intervals
    df_quantiles.loc[df_quantiles[ci_lower] > df_preds, ci_lower] = df_preds
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops/__init__.py", line 524, in wrapper
    raise ValueError("Can only compare identically-labeled Series objects")
ValueError: Can only compare identically-labeled Series objects
```

**Comment by isaacmg** [comment]
My guess is that this related to a difference in column names. Going to add print statement

**Comment by isaacmg** [comment]
`ValueError: operands could not be broadcast together with shapes (336,) (338,) `
